Table dim_date {
  date_key int [pk]
  date date
  year int
  quarter int
  month int
  month_start date
  month_name varchar
}

Table dim_customer {
  customer_id int [pk]
  customer_name varchar
  investor_profile varchar
  city varchar
  state varchar
  birth_date date
  signup_date date
}

Table dim_fund {
  fund_key varchar [pk]
  fund_name varchar
  fund_type varchar
  risk_bucket varchar
}

Table fact_transactions {
  transaction_id int [pk]
  date_key int [ref: > dim_date.date_key]
  customer_id int [ref: > dim_customer.customer_id]
  account_id int
  fund_key varchar [ref: > dim_fund.fund_key]
  transaction_type varchar
  amount decimal
  application_amount decimal
  redemption_amount decimal
  net_flow_amount decimal
}

Table fact_public_fund_monthly {
  fund_cnpj varchar
  month_start date
  public_fund_name varchar
  net_worth decimal
  monthly_application decimal
  monthly_redemption decimal
  monthly_net_flow decimal
  quota_holders int
  monthly_return decimal
  volatility decimal

  indexes {
    (fund_cnpj, month_start) [pk]
  }
}

Table fact_macro_monthly {
  month_start date [pk]
  selic_monthly_pct decimal
  ipca_monthly_pct decimal
}

Table fact_market_monthly {
  ticker varchar
  month_start date
  month_close decimal
  monthly_return decimal
  volatility decimal

  indexes {
    (ticker, month_start) [pk]
  }
}

